### ISSUE TITLE
Android 11（API level 30） java.lang.SecurityException: getDataNetworkTypeForSubscriber

### ISSUE THREAD

**Issue by yann02** [TencentCloud/tencentcloud-sdk-android-soe#8]
--logversion:utracea
Process Name: 'com.***'
Thread Name: 'Thread-48'
Back traces starts.
java.lang.SecurityException: getDataNetworkTypeForSubscriber
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2389)
	at android.os.Parcel.createException(Parcel.java:2373)
	at android.os.Parcel.readException(Parcel.java:2356)
	at android.os.Parcel.readException(Parcel.java:2298)
	at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8762)
	at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3024)
	at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2988)
	at com.tencent.taisdkinner.c.a(Unknown Source:55)
	at com.tencent.taisdkinner.l.a(Unknown Source:12)
	at com.tencent.taisdkinner.h$b.a(Unknown Source:347)
	at com.tencent.taisdkinner.d$a.run(Unknown Source:207)
	at java.lang.Thread.run(Thread.java:923)
Back traces ends.

**Comment by yann02** [comment]
https://developer.android.google.cn/about/versions/11/privacy/permissions#phone-numbers
盼升级一下，项目目前已经上线。

**Comment by mm46468648** [comment]
2023了这个问题是不是还没有修复啊。

**Comment by kennethmiao** [comment]
> 2023了这个问题是不是还没有修复啊。

你好，请问使用的是哪个版本呢？目前使用最新版本（1.2.3.110）使用Android11 API30未复现此问题
